name: Laravel

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, bcmath, sqlite

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate Key
        run: php artisan key:generate

      - name: Set Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite DB
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Run Migration
        run: php artisan migrate --force

      # ✅ TAMBAHAN PENTING
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Vite Assets
        run: npm run build

      - name: Run Tests
        run: php artisan test